# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoplecvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
