# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=765)),
                ('emblem', models.ImageField(null=True, upload_to='people/photos')),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ('party_name',),
            },
        ),
    ]
