# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("parties", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="emblem",
            field=models.ImageField(null=True, upload_to="parties/emblems"),
        )
    ]
