# Generated by Django 2.2.7 on 2019-11-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("news_mentions", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="ballotnewsarticle",
            name="publisher",
            field=models.CharField(blank=True, max_length=500),
        )
    ]
