# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ynr_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField()),
                ('party_name', models.CharField(blank=True, max_length=255)),
                ('post', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
