# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0003_auto_20160414_0704")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="facebook_page_url",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="facebook_personal_url",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="homepage_url",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="twitter_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="wikipedia_url",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
