# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_person_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
