# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_personpost_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='party',
        ),
    ]
