# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_election_for_post_role'),
        ('people', '0006_personpost_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpost',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.Election'),
        ),
    ]
