# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_remove_person_party'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personpost',
            options={'ordering': ('-election__election_date',)},
        ),
    ]
