# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_post'),
        ('people', '0008_auto_20160324_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='post',
        ),
        migrations.AddField(
            model_name='person',
            name='posts',
            field=models.ManyToManyField(to='elections.Post'),
        ),
        migrations.AlterField(
            model_name='person',
            name='election',
            field=models.ManyToManyField(to='elections.Election'),
        ),
    ]
