# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_auto_20170304_1354'),
        ('people', '0009_auto_20170303_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personpost',
            unique_together=set([('person', 'post', 'election')]),
        ),
    ]
