# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0011_person_statement_to_voters")]

    operations = [
        migrations.RemoveField(model_name="person", name="photo"),
        migrations.AddField(
            model_name="person",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
