# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20170515_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ynr_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
