# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("people", "0013_auto_20170515_2047")]

    operations = [
        migrations.AlterField(
            model_name="personpost",
            name="election",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="elections.Election",
            ),
        ),
        migrations.AlterField(
            model_name="personpost",
            name="party",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="parties.Party",
            ),
        ),
        migrations.AlterField(
            model_name="personpost",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="personpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="elections.Post",
            ),
        ),
    ]
