# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20170518_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpost',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elections.Election'),
        ),
    ]
