# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0019_associatedcompany")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="favourite_biscuit",
            field=models.CharField(max_length=800, null=True),
        )
    ]
