# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_auto_20170605_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='degree_cat',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='field_postgrad',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='field_undergrad',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_or_current_job',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='previously_in_parliament',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='secondary_school',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='stem_postgrad',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='stem_undergrad',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='university_postgrad',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='university_undergrad',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
