# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_auto_20170605_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpost',
            name='elected',
            field=models.NullBooleanField(),
        ),
    ]
