# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_post_election(apps, schema_editor):
    PersonPost = apps.get_model('people', 'PersonPost')
    PostElection = apps.get_model('elections', 'PostElection')
    post_election_cache = {}
    for post_election in PostElection.objects.all():
        PersonPost.objects.filter(
            election=post_election.election,
            post=post_election.post
        ).update(
            post_election=post_election
        )

    for person_post in PersonPost.objects.filter(post_election=None):
        person_post.post_election = PostElection.objects.get(
            election=person_post.election,
            post=person_post.post,
        )
        person_post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0020_postelection_ballot_paper_id'),
        ('people', '0024_personpost_elected'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpost',
            name='post_election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.PostElection'),
        ),
        migrations.RunPython(add_post_election, migrations.RunPython.noop)

    ]
