# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0026_auto_20180417_1944")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="party_ppc_page_url",
            field=models.CharField(blank=True, max_length=800, null=True),
        )
    ]
