# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_person_pk_to_int'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'get_latest_by': 'last_updated'},
        ),
        migrations.AddField(
            model_name='person',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
