# Generated by Django 2.2.4 on 2019-10-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0029_person_last_updated")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="instagram_id",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="instagram_url",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="youtube_profile",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
