# Generated by Django 2.2.7 on 2019-11-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0030_insta-youtube")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="sort_name",
            field=models.CharField(max_length=255, null=True),
        )
    ]
