# Generated by Django 2.2.7 on 2019-12-11 14:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0032_person_death_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookAdvert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_id",
                    models.CharField(
                        help_text="The Facebook ID for this advert",
                        max_length=500,
                    ),
                ),
                (
                    "ad_json",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        help_text="The JSON returned from the Facebook Graph API for this advert"
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.Person",
                    ),
                ),
            ],
        ),
    ]
