# Generated by Django 2.2.7 on 2019-12-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0033_facebookadvert"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facebookadvert",
            options={
                "get_latest_by": "ad_json__ad_delivery_start_time",
                "ordering": ("-ad_json__ad_delivery_start_time",),
            },
        ),
    ]
