# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hustings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husting',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.PostElection'),
        ),
    ]
