# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hustings', '0002_auto_20170514_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='husting',
            old_name='post',
            new_name='post_election',
        ),
    ]
