# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mention',
            options={'ordering': ['-date_published']},
        ),
    ]
