# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20160326_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
