# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0005_election_election_type")]

    operations = [
        migrations.AddField(
            model_name="votingsystem",
            name="uses_lists",
            field=models.BooleanField(default=False),
        )
    ]
