# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_votingsystem_uses_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingsystem',
            name='uses_lists',
        ),
        migrations.AddField(
            model_name='election',
            name='uses_lists',
            field=models.BooleanField(default=False),
        ),
    ]
