# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0007_auto_20160405_0857")]

    operations = [
        migrations.AddField(
            model_name="election",
            name="voter_age",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="election",
            name="voter_citizenship",
            field=models.TextField(blank=True),
        ),
    ]
