# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0008_auto_20160405_1412")]

    operations = [
        migrations.AddField(
            model_name="election",
            name="for_post_role",
            field=models.TextField(blank=True),
        )
    ]
