# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_auto_20160502_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='election',
        ),
        migrations.AddField(
            model_name='post',
            name='elections',
            field=models.ManyToManyField(to='elections.Election'),
        ),
    ]
