# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0012_auto_20170304_1351")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="elections2",
            field=models.ManyToManyField(
                through="elections.PostElection", to="elections.Election"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="elections",
            field=models.ManyToManyField(related_name="fake", to="elections.Election"),
        ),
    ]
