# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("elections", "0013_auto_20170304_1354")]

    operations = [migrations.RemoveField(model_name="post", name="elections")]
