# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("elections", "0014_remove_post_elections")]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="elections2", new_name="elections"
        )
    ]
