# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_auto_20170304_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='postelection',
            name='contested',
            field=models.BooleanField(default=True),
        ),
    ]
