# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0017_parl-2017-06-08-weight")]

    operations = [
        migrations.AddField(
            model_name="postelection",
            name="locked",
            field=models.BooleanField(default=False),
        )
    ]
