# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 12:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("elections", "0018_postelection_locked")]

    operations = [
        migrations.AddField(
            model_name="election",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        )
    ]
