# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0020_postelection_ballot_paper_id")]

    operations = [
        migrations.AddField(
            model_name="postelection",
            name="winner_count",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
