# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0023_election_any_non_by_elections")]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="any_non_by_elections",
            field=models.BooleanField(default=False),
        )
    ]
