# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("elections", "0025_auto_20190412_1528")]

    operations = [
        migrations.AddField(
            model_name="postelection",
            name="voting_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.VotingSystem",
            ),
        )
    ]
