# Generated by Django 2.2.7 on 2019-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0028_add_territory_to_posts")]

    operations = [
        migrations.AddField(
            model_name="postelection",
            name="wikipedia_bio",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="postelection",
            name="wikipedia_url",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
