# Generated by Django 2.2.7 on 2020-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0029_wikipedia_on_ballot"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="organization_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
