# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("pledges", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="candidatepledge",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pledges",
                to="people.Person",
            ),
        )
    ]
